// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import AutoSubmitController from "./auto_submit_controller"
application.register("auto-submit", AutoSubmitController)

import BookBrowserController from "./book_browser_controller"
application.register("book-browser", BookBrowserController)

import AiSearchController from "./ai_search_controller"
application.register("ai-search", AiSearchController)

import XrefController from "./xref_controller"
application.register("xref", XrefController)

import NotesController from "./notes_controller"
application.register("notes", NotesController)

import HighlighterController from "./highlighter_controller"
application.register("highlighter", HighlighterController)

import ShortcutsController from "./shortcuts_controller"
application.register("shortcuts", ShortcutsController)

import AuthGateController from "./auth_gate_controller"
application.register("auth-gate", AuthGateController)

import NewStudyController from "./new_study_controller"
application.register("new-study", NewStudyController)
